server:
  port: 6060

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example.demo.pojo.*


spring:
  datasource:
    name: louder
    url: jdbc:mysql://121.5.27.43:3306/louder
    username: root
    password: louder123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 100
    host: 121.5.27.43
    password: louder123
    port: 6379
    timeout: 5000
  data:
    elasticsearch:
      repositories:
        enabled: true



rocketmq:
  name-server: 121.5.27.43:9876

redisson:



